"""跑 N 场景 LongCat 测试，输出 JSON 给 HTML 渲染用。"""
from __future__ import annotations
import sys, time, json, traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from agents.planner import plan as make_plan
from agents.replanner import probe_plan
from agents.types import UserPreferences
from tools.mock_message import render_im_card
from tools.tool_call_log import set_session, clear_session, fetch_calls


SCENARIOS = [
    # ---------- family（10 个，含 with_child + 不同年龄 + 不同片区）----------
    {"id":"S01","title":"亲子周末·五道营","persona":"family","area":"五道营-雍和宫片区",
     "user_input":"今天下午带老婆和 5 岁娃出去玩，别离家太远，4 小时左右。老婆减脂，娃喜欢动物。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=5,diet_flags=["light_diet"],walk_radius_km=1.5,budget_per_person=120,target_start="14:00",duration_hours=4.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S02","title":"亲子文化·安定门V3","persona":"family","area":"安定门片区V3",
     "user_input":"周日带爸妈和娃逛胡同看古迹，不要太晒，要有座位歇脚。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=8,walk_radius_km=1.2,budget_per_person=150,target_start="14:00",duration_hours=4.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S03","title":"亲子科普·奥森","persona":"family","area":"奥林匹克公园片区",
     "user_input":"周六上午带 3 岁娃去看动物科普展，孩子能跑能玩，中午吃顿好的。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=3,walk_radius_km=2.0,budget_per_person=200,target_start="10:00",duration_hours=4.0),
     "audience":"spouse","contact":"娃他妈"},
    {"id":"S04","title":"亲子赏景·什刹海","persona":"family","area":"什刹海-鼓楼片区",
     "user_input":"娃想看湖景拍照，老人腿脚不太利索，全程慢节奏。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=6,walk_radius_km=1.0,budget_per_person=130,target_start="14:30",duration_hours=3.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S05","title":"亲子城市游·三里屯V3","persona":"family","area":"三里屯片区V3",
     "user_input":"周日下午想带娃去三里屯感受下时尚，但别太吵，预算松。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=10,walk_radius_km=1.5,budget_per_person=300,target_start="14:00",duration_hours=4.0),
     "audience":"spouse","contact":"@老婆"},
    {"id":"S06","title":"亲子文化·王府井","persona":"family","area":"王府井-东单片区",
     "user_input":"娃刚学完明清史，想看看故宫边上的老北京，简单吃顿炸酱面。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=11,walk_radius_km=1.5,budget_per_person=120,target_start="14:00",duration_hours=4.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S07","title":"亲子轻量·西单V3","persona":"family","area":"西单片区V3",
     "user_input":"老婆带俩娃，要近不要赶，下午出来散步顺便逛逛。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=7,walk_radius_km=1.0,budget_per_person=100,target_start="15:00",duration_hours=3.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S08","title":"亲子摄影·东直门V3","persona":"family","area":"东直门片区V3",
     "user_input":"想给娃拍套生日大片，下午光好的时候出门，4 小时。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=4,walk_radius_km=1.5,budget_per_person=180,target_start="15:00",duration_hours=4.0),
     "audience":"spouse","contact":"娃妈"},
    {"id":"S09","title":"亲子博物馆·东四V3","persona":"family","area":"东四片区V3",
     "user_input":"娃喜欢恐龙，老婆喜欢逛胡同小店，找个能两个人都开心的下午。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=8,walk_radius_km=1.5,budget_per_person=150,target_start="13:30",duration_hours=4.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S10","title":"亲子赏花·景山","persona":"family","area":"景山-什刹海片区",
     "user_input":"娃要去看银杏，老婆要拍照，老人腿脚一般，2 小时内能走完。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=9,walk_radius_km=0.8,budget_per_person=100,target_start="15:00",duration_hours=2.5),
     "audience":"spouse","contact":"老婆"},

    # ---------- friends（10 个）----------
    {"id":"S11","title":"朋友聚会·三里屯V3","persona":"friends","area":"三里屯片区V3",
     "user_input":"跟 4 个朋友周六下午出去玩，2 男 2 女，别太赶，能聊天。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=2.0,budget_per_person=250,target_start="14:30",duration_hours=5.0),
     "audience":"friend","contact":"@小张"},
    {"id":"S12","title":"朋友城市游·王府井","persona":"friends","area":"王府井-东单片区",
     "user_input":"周六下午 3 个同事逛街顺便吃饭，预算别太离谱。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.5,budget_per_person=180,target_start="14:30",duration_hours=4.5),
     "audience":"friend","contact":"@同事群"},
    {"id":"S13","title":"朋友咖啡探店·五道口V3","persona":"friends","area":"五道口片区V3",
     "user_input":"和朋友约咖啡探店，要文艺安静，能聊 3 小时。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.0,budget_per_person=150,target_start="14:00",duration_hours=3.5),
     "audience":"friend","contact":"@阿楠"},
    {"id":"S14","title":"朋友夜生活·三里屯V3","persona":"friends","area":"三里屯片区V3",
     "user_input":"周五晚上跟朋友放松一下，吃饭聊天看夜景。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.5,budget_per_person=300,target_start="18:30",duration_hours=4.0),
     "audience":"friend","contact":"@老李"},
    {"id":"S15","title":"朋友逛展·望京V3","persona":"friends","area":"望京片区V3",
     "user_input":"周末跟朋友逛设计展加咖啡店，悠闲点。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.5,budget_per_person=200,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"@小敏"},
    {"id":"S16","title":"朋友美食·珠市口V3","persona":"friends","area":"珠市口片区V3",
     "user_input":"想跟朋友吃点京味小吃，再消食散步。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=1.5,budget_per_person=150,target_start="17:00",duration_hours=4.0),
     "audience":"friend","contact":"@美食群"},
    {"id":"S17","title":"朋友 city walk·西单V3","persona":"friends","area":"西单片区V3",
     "user_input":"3 个朋友周日下午走走，逛逛潮店买点东西。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=2.0,budget_per_person=400,target_start="14:00",duration_hours=4.5),
     "audience":"friend","contact":"@闺蜜群"},
    {"id":"S18","title":"朋友文化·什刹海","persona":"friends","area":"什刹海-鼓楼片区",
     "user_input":"跟朋友逛胡同酒吧，从下午到晚上。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.5,budget_per_person=280,target_start="16:00",duration_hours=5.0),
     "audience":"friend","contact":"@小马"},
    {"id":"S19","title":"朋友 brunch·亮马桥V3","persona":"friends","area":"亮马桥片区V3",
     "user_input":"周日跟闺蜜吃 brunch 顺便逛精品店。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.5,budget_per_person=350,target_start="11:00",duration_hours=4.0),
     "audience":"friend","contact":"@闺蜜"},
    {"id":"S20","title":"朋友体育休闲·国贸V3","persona":"friends","area":"国贸片区V3",
     "user_input":"和同事打完羽毛球后吃个饭，别离场地太远。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=1.5,budget_per_person=180,target_start="17:30",duration_hours=3.0),
     "audience":"friend","contact":"@球友群"},

    # ---------- solo（10 个）----------
    {"id":"S21","title":"独自慢游·五道营","persona":"solo","area":"五道营-雍和宫片区",
     "user_input":"自己来北京出差，下午有 3 小时，想感受一下老北京。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=150,target_start="14:00",duration_hours=3.0),
     "audience":"friend","contact":"自己"},
    {"id":"S22","title":"独自咖啡·东四V3","persona":"solo","area":"东四片区V3",
     "user_input":"想找家有意思的咖啡馆静静坐一下午，能写点东西。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=100,target_start="14:30",duration_hours=4.0),
     "audience":"friend","contact":"自己"},
    {"id":"S23","title":"独自逛展·798","persona":"solo","area":"798-酒仙桥艺术区",
     "user_input":"周末一个人想看展，再吃个不油腻的饭。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=180,target_start="13:00",duration_hours=5.0),
     "audience":"friend","contact":"自己"},
    {"id":"S24","title":"独自摄影·什刹海","persona":"solo","area":"什刹海-后海片区",
     "user_input":"一个人下午去拍照，要好出片的角度。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=120,target_start="15:00",duration_hours=3.0),
     "audience":"friend","contact":"自己"},
    {"id":"S25","title":"独自夜游·王府井","persona":"solo","area":"王府井-东单片区",
     "user_input":"出差晚上有空，吃顿正经北京菜再随便逛逛。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=200,target_start="18:00",duration_hours=3.5),
     "audience":"friend","contact":"自己"},
    {"id":"S26","title":"独自学习·五道口V3","persona":"solo","area":"五道口片区V3",
     "user_input":"自习换换环境，找个安静咖啡馆一下午，附近有饭店就行。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=100,target_start="13:30",duration_hours=5.0),
     "audience":"friend","contact":"自己"},
    {"id":"S27","title":"独自健身·朝阳V3","persona":"solo","area":"朝阳区片区V3",
     "user_input":"运动完想吃高蛋白低油的，离健身房不要太远。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=120,target_start="18:30",duration_hours=2.0),
     "audience":"friend","contact":"自己"},
    {"id":"S28","title":"独自慢节奏·沙滩V3","persona":"solo","area":"沙滩片区V3",
     "user_input":"想找个有历史感的地方走走，不太热闹的。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=130,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"自己"},
    {"id":"S29","title":"独自夜跑路线·奥森","persona":"solo","area":"奥林匹克公园片区",
     "user_input":"下班想去奥森溜达一圈，结束后吃顿轻食。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.5,budget_per_person=80,target_start="18:00",duration_hours=2.5),
     "audience":"friend","contact":"自己"},
    {"id":"S30","title":"独自小吃·大栅栏V3","persona":"solo","area":"大栅栏片区V3",
     "user_input":"想去大栅栏吃小吃，再走走老胡同。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=80,target_start="16:00",duration_hours=3.0),
     "audience":"friend","contact":"自己"},

    # ---------- with_parents（10 个）----------
    {"id":"S31","title":"陪父母赏景·景山","persona":"with_parents","area":"景山-什刹海片区",
     "user_input":"周末带爸妈去景山看皇城，老人不能走太久。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=120,target_start="14:00",duration_hours=3.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S32","title":"陪父母吃馆·王府井","persona":"with_parents","area":"王府井-东单片区",
     "user_input":"陪爸妈在王府井吃顿正经的，再带他们逛逛。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=200,target_start="11:30",duration_hours=4.0),
     "audience":"friend","contact":"我爸"},
    {"id":"S33","title":"陪父母京味·珠市口V3","persona":"with_parents","area":"珠市口片区V3",
     "user_input":"老人想吃京味小吃，再走走老胡同，3 小时左右。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=130,target_start="14:00",duration_hours=3.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S34","title":"陪父母慢游·什刹海","persona":"with_parents","area":"什刹海-鼓楼片区",
     "user_input":"带父母看后海，要有椅子歇脚。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.8,budget_per_person=120,target_start="14:30",duration_hours=3.5),
     "audience":"friend","contact":"我爸"},
    {"id":"S35","title":"陪父母上香·安定门V3","persona":"with_parents","area":"安定门片区V3",
     "user_input":"我妈想去雍和宫上香，周边能吃顿素斋。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=150,target_start="10:00",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S36","title":"陪父母博物馆·天安门","persona":"with_parents","area":"天安门-故宫片区",
     "user_input":"带爸妈逛国博，结束后慢慢吃个饭。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=180,target_start="13:00",duration_hours=5.0),
     "audience":"friend","contact":"我爸"},
    {"id":"S37","title":"陪父母散步·东城V3","persona":"with_parents","area":"东城区片区V3",
     "user_input":"带老人散散步，吃口热乎的，不要赶。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.8,budget_per_person=120,target_start="15:00",duration_hours=3.0),
     "audience":"friend","contact":"我爸妈"},
    {"id":"S38","title":"陪父母看展·西城V3","persona":"with_parents","area":"西城区片区V3",
     "user_input":"陪老人看场不太累的展览，吃饭别太远。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=160,target_start="13:30",duration_hours=4.0),
     "audience":"friend","contact":"我爸"},
    {"id":"S39","title":"陪父母赏秋·奥森","persona":"with_parents","area":"奥林匹克公园片区",
     "user_input":"带爸妈秋天去奥森看银杏，回来吃个家常菜。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.5,budget_per_person=140,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S40","title":"陪父母老字号·大栅栏V3","persona":"with_parents","area":"大栅栏片区V3",
     "user_input":"带父母去大栅栏吃老字号，看看老北京。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=160,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"我爸"},

    # ============================================================
    # [12] eval 扩到 100 — S41-S100：边缘 case 覆盖
    # ============================================================
    # ---------- family 续（15 个，S41-S55，含 雨天 / 高预算 / 极短 / 极长 / 婴幼儿）----------
    {"id":"S41","title":"亲子高预算·三里屯V3","persona":"family","area":"三里屯片区V3",
     "user_input":"带娃去三里屯过 5 岁生日，预算松点，要有蛋糕和拍照点。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=5,walk_radius_km=1.5,budget_per_person=600,target_start="14:00",duration_hours=4.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S42","title":"亲子极低预算·东四V3","persona":"family","area":"东四片区V3",
     "user_input":"带俩娃出门，钱不多，找个不花钱的地方逛逛。",
     "prefs":dict(persona="family",party_size=4,has_child=True,child_age=8,walk_radius_km=1.0,budget_per_person=40,target_start="14:00",duration_hours=3.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S43","title":"亲子婴幼儿·北海","persona":"family","area":"北海-景山联动片区",
     "user_input":"带 2 岁宝宝出门，要有母婴室和遮阳。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=2,walk_radius_km=0.8,budget_per_person=150,target_start="10:00",duration_hours=3.0),
     "audience":"spouse","contact":"娃妈"},
    {"id":"S44","title":"亲子早起·南锣鼓巷","persona":"family","area":"南锣鼓巷片区",
     "user_input":"早晨带娃逛胡同吃早点，避开人多时段。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=7,walk_radius_km=1.5,budget_per_person=100,target_start="08:30",duration_hours=3.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S45","title":"亲子素食·五道营V3","persona":"family","area":"五道营-雍和宫片区",
     "user_input":"我们一家信佛吃素，找雍和宫附近素菜馆带娃过下午。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=6,diet_flags=["vegetarian"],walk_radius_km=1.2,budget_per_person=130,target_start="14:00",duration_hours=4.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S46","title":"亲子户外·奥森","persona":"family","area":"奥林匹克公园片区",
     "user_input":"带娃去奥森骑车跑步，结束后吃简单的。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=10,walk_radius_km=2.5,budget_per_person=120,target_start="15:00",duration_hours=4.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S47","title":"亲子科技馆·中关村V3","persona":"family","area":"中关村片区V3",
     "user_input":"娃要看科技馆 / 自然博物馆，结束附近吃饭。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=9,walk_radius_km=1.5,budget_per_person=160,target_start="13:00",duration_hours=5.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S48","title":"亲子上海菜·簋街","persona":"family","area":"东直门-簋街片区",
     "user_input":"娃想吃小笼包，老婆喜欢清淡，最好是上海菜。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=6,diet_flags=["light_diet","no_spicy"],walk_radius_km=1.5,budget_per_person=180,target_start="17:00",duration_hours=3.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S49","title":"亲子图书馆·西单V3","persona":"family","area":"西单片区V3",
     "user_input":"周末娃想看书，带他去图书馆 + 书店，再吃点心。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=11,walk_radius_km=1.5,budget_per_person=120,target_start="14:00",duration_hours=4.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S50","title":"亲子海洋馆·安定门V3","persona":"family","area":"安定门片区V3",
     "user_input":"周末带 4 岁娃看动物，午饭得娃能吃。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=4,walk_radius_km=2.0,budget_per_person=130,target_start="10:00",duration_hours=5.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S51","title":"亲子寒冬·什刹海V3","persona":"family","area":"什刹海片区V3",
     "user_input":"冬天带娃出来，要室内为主，别冻着。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=8,walk_radius_km=1.0,budget_per_person=150,target_start="14:00",duration_hours=3.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S52","title":"亲子雨天·西城V3","persona":"family","area":"西城区片区V3",
     "user_input":"今天下雨，带娃要室内的能避雨的去处。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=7,walk_radius_km=0.8,budget_per_person=140,target_start="14:00",duration_hours=3.0),
     "audience":"spouse","contact":"老婆"},
    {"id":"S53","title":"亲子超长游·朝阳V3","persona":"family","area":"朝阳区片区V3",
     "user_input":"周日全天带娃，从午饭一直玩到晚饭，6 小时。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=8,walk_radius_km=2.0,budget_per_person=200,target_start="11:30",duration_hours=6.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S54","title":"亲子超短游·建国门V3","persona":"family","area":"建国门片区V3",
     "user_input":"娃要午睡，下午就 1.5 小时空，带他逛逛。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=4,walk_radius_km=0.6,budget_per_person=80,target_start="15:30",duration_hours=1.5),
     "audience":"spouse","contact":"老婆"},
    {"id":"S55","title":"亲子骑行·亮马桥V3","persona":"family","area":"亮马桥片区V3",
     "user_input":"娃会骑车，沿亮马河带他骑一圈，再吃顿西餐。",
     "prefs":dict(persona="family",party_size=3,has_child=True,child_age=10,walk_radius_km=2.0,budget_per_person=250,target_start="14:30",duration_hours=4.0),
     "audience":"spouse","contact":"老婆"},

    # ---------- friends 续（15 个，S56-S70）----------
    {"id":"S56","title":"朋友高奢·国贸","persona":"friends","area":"国贸-CBD片区",
     "user_input":"3 个朋友升职庆功，国贸高端餐厅 + 红酒，预算松。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.5,budget_per_person=800,target_start="18:30",duration_hours=4.0),
     "audience":"friend","contact":"@同事"},
    {"id":"S57","title":"朋友穷游·五道口V3","persona":"friends","area":"五道口片区V3",
     "user_input":"学生党朋友聚会，便宜实惠，能吃饱就行。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=1.5,budget_per_person=50,target_start="17:00",duration_hours=3.5),
     "audience":"friend","contact":"@同学"},
    {"id":"S58","title":"朋友烧烤·鼓楼","persona":"friends","area":"鼓楼-钟楼片区",
     "user_input":"朋友来北京想吃烧烤喝啤酒，胡同里有特色的。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=1.5,budget_per_person=200,target_start="18:00",duration_hours=4.0),
     "audience":"friend","contact":"@老同学"},
    {"id":"S59","title":"朋友 brunch·望京V3","persona":"friends","area":"望京-韩国街片区",
     "user_input":"周末和闺蜜在望京吃个韩餐 brunch，再逛逛。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.5,budget_per_person=180,target_start="11:00",duration_hours=4.0),
     "audience":"friend","contact":"@闺蜜"},
    {"id":"S60","title":"朋友雨天·东直门V3","persona":"friends","area":"东直门片区V3",
     "user_input":"今天下雨，跟朋友找室内的咖啡馆 + 餐厅。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=0.8,budget_per_person=200,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"@老李"},
    {"id":"S61","title":"朋友工作日·金融街V3","persona":"friends","area":"金融街片区V3",
     "user_input":"工作日中午跟朋友吃个饭，得快，1.5 小时。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=0.8,budget_per_person=150,target_start="12:00",duration_hours=1.5),
     "audience":"friend","contact":"@同事"},
    {"id":"S62","title":"朋友夜跑+夜宵·朝阳公园","persona":"friends","area":"朝阳公园片区",
     "user_input":"和朋友先去朝阳公园跑跑步，再撸串。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=2.0,budget_per_person=180,target_start="18:00",duration_hours=4.0),
     "audience":"friend","contact":"@球友"},
    {"id":"S63","title":"朋友书店·美术馆","persona":"friends","area":"中国美术馆-五四大街片区",
     "user_input":"和朋友逛三联书店和美术馆，晚上吃顿东四的饭。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.5,budget_per_person=180,target_start="14:30",duration_hours=4.5),
     "audience":"friend","contact":"@阿楠"},
    {"id":"S64","title":"朋友茶馆·什刹海V3","persona":"friends","area":"什刹海片区V3",
     "user_input":"和朋友找个安静茶馆聊一下午，再去酒吧。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.5,budget_per_person=220,target_start="14:00",duration_hours=5.5),
     "audience":"friend","contact":"@小敏"},
    {"id":"S65","title":"朋友清真·牛街V3","persona":"friends","area":"牛街片区V3",
     "user_input":"和回族朋友聚会，要清真餐厅，再走走。",
     "prefs":dict(persona="friends",party_size=3,diet_flags=["halal"],walk_radius_km=1.0,budget_per_person=150,target_start="17:00",duration_hours=3.5),
     "audience":"friend","contact":"@阿里"},
    {"id":"S66","title":"朋友海鲜·簋街","persona":"friends","area":"东直门-簋街片区",
     "user_input":"朋友想吃麻小，簋街找最有名的，能等位。",
     "prefs":dict(persona="friends",party_size=3,walk_radius_km=1.0,budget_per_person=300,target_start="17:30",duration_hours=4.0),
     "audience":"friend","contact":"@老张"},
    {"id":"S67","title":"朋友火锅·大望路V3","persona":"friends","area":"大望路片区V3",
     "user_input":"周末和朋友吃火锅，4 个人，要大众点评高评分的。",
     "prefs":dict(persona="friends",party_size=4,walk_radius_km=1.0,budget_per_person=200,target_start="17:30",duration_hours=4.0),
     "audience":"friend","contact":"@大龙"},
    {"id":"S68","title":"朋友无辣·东单V3","persona":"friends","area":"东单片区V3",
     "user_input":"和南方朋友聚，他们怕辣，找清淡好吃的粤菜或淮扬。",
     "prefs":dict(persona="friends",party_size=3,diet_flags=["no_spicy"],walk_radius_km=1.0,budget_per_person=250,target_start="18:00",duration_hours=3.5),
     "audience":"friend","contact":"@小陈"},
    {"id":"S69","title":"朋友咖啡马拉松·王府井V3","persona":"friends","area":"王府井片区V3",
     "user_input":"和闺蜜咖啡 hopping，连刷 3 家精品咖啡。",
     "prefs":dict(persona="friends",party_size=2,walk_radius_km=1.5,budget_per_person=200,target_start="13:30",duration_hours=5.0),
     "audience":"friend","contact":"@闺蜜"},
    {"id":"S70","title":"朋友 KTV·三里屯V3","persona":"friends","area":"三里屯片区V3",
     "user_input":"5 个朋友吃完饭去 KTV，要走得近。",
     "prefs":dict(persona="friends",party_size=5,walk_radius_km=1.0,budget_per_person=250,target_start="18:30",duration_hours=5.0),
     "audience":"friend","contact":"@群"},

    # ---------- solo 续（15 个，S71-S85）----------
    {"id":"S71","title":"独自高预算·亮马桥V3","persona":"solo","area":"亮马桥片区V3",
     "user_input":"自己出差犒劳，预算松，找米其林一家慢慢吃。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=1000,target_start="18:00",duration_hours=3.0),
     "audience":"friend","contact":"自己"},
    {"id":"S72","title":"独自极简·和平里V3","persona":"solo","area":"和平里-地坛西片区",
     "user_input":"一个人随便走走，¥50 以内吃完逛完。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=50,target_start="14:00",duration_hours=2.5),
     "audience":"friend","contact":"自己"},
    {"id":"S73","title":"独自考研图书馆·五道口V3","persona":"solo","area":"五道口片区V3",
     "user_input":"自习一整天，下午找咖啡馆专注 5 小时。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=80,target_start="13:00",duration_hours=5.5),
     "audience":"friend","contact":"自己"},
    {"id":"S74","title":"独自夜游·簋街","persona":"solo","area":"簋街片区",
     "user_input":"晚上一个人去簋街吃个小龙虾，要营业到 22 点的。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=180,target_start="20:00",duration_hours=2.0),
     "audience":"friend","contact":"自己"},
    {"id":"S75","title":"独自雨天·三里屯V3","persona":"solo","area":"三里屯片区V3",
     "user_input":"今天下雨，自己窝室内逛三里屯太古里加吃饭。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=0.8,budget_per_person=200,target_start="14:00",duration_hours=3.5),
     "audience":"friend","contact":"自己"},
    {"id":"S76","title":"独自宫殿·天安门","persona":"solo","area":"天安门-故宫片区",
     "user_input":"自己来北京 3 天，下午就想看故宫和周边。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=150,target_start="13:00",duration_hours=5.0),
     "audience":"friend","contact":"自己"},
    {"id":"S77","title":"独自素食·雍和宫","persona":"solo","area":"五道营-雍和宫片区",
     "user_input":"独自吃素，下午找个素菜馆 + 雍和宫上香。",
     "prefs":dict(persona="solo",party_size=1,diet_flags=["vegetarian"],walk_radius_km=1.0,budget_per_person=130,target_start="14:00",duration_hours=3.5),
     "audience":"friend","contact":"自己"},
    {"id":"S78","title":"独自小酌·南锣","persona":"solo","area":"南锣鼓巷片区",
     "user_input":"一个人安静喝点酒，找有特色的小酒馆。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=180,target_start="19:00",duration_hours=3.0),
     "audience":"friend","contact":"自己"},
    {"id":"S79","title":"独自拍摄·北海","persona":"solo","area":"北海片区V3",
     "user_input":"摄影师，下午自己去北海拍人像，再吃点。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=120,target_start="15:00",duration_hours=3.5),
     "audience":"friend","contact":"自己"},
    {"id":"S80","title":"独自健身后·三里屯V3","persona":"solo","area":"三里屯片区V3",
     "user_input":"健身完一个人吃高蛋白，便宜些 ¥80 内。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=0.8,budget_per_person=80,target_start="19:00",duration_hours=1.5),
     "audience":"friend","contact":"自己"},
    {"id":"S81","title":"独自老胡同·法源寺","persona":"solo","area":"陶然亭片区",
     "user_input":"自己想去看法源寺逛胡同 + 吃口炸酱面。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=80,target_start="14:00",duration_hours=3.5),
     "audience":"friend","contact":"自己"},
    {"id":"S82","title":"独自清晨·景山","persona":"solo","area":"景山-什刹海片区",
     "user_input":"自己早上去景山看日出，吃个北京早点。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=60,target_start="06:30",duration_hours=3.0),
     "audience":"friend","contact":"自己"},
    {"id":"S83","title":"独自购物·西单V3","persona":"solo","area":"西单片区V3",
     "user_input":"自己逛西单买东西 + 吃个饭。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.0,budget_per_person=200,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"自己"},
    {"id":"S84","title":"独自展览·798","persona":"solo","area":"798艺术区",
     "user_input":"自己去 798 看新展，结束吃个轻食。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=2.0,budget_per_person=180,target_start="13:30",duration_hours=4.5),
     "audience":"friend","contact":"自己"},
    {"id":"S85","title":"独自小吃·大栅栏V3","persona":"solo","area":"大栅栏片区V3",
     "user_input":"自己去大栅栏一路尝小吃，吃到撑。",
     "prefs":dict(persona="solo",party_size=1,walk_radius_km=1.5,budget_per_person=150,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"自己"},

    # ---------- with_parents 续（15 个，S86-S100）----------
    {"id":"S86","title":"陪父母素斋·雍和宫","persona":"with_parents","area":"五道营-雍和宫片区",
     "user_input":"陪我妈来雍和宫上香吃素斋，再喝个茶。",
     "prefs":dict(persona="with_parents",party_size=3,diet_flags=["vegetarian"],walk_radius_km=1.0,budget_per_person=140,target_start="10:30",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S87","title":"陪父母慢节奏·西单V3","persona":"with_parents","area":"西单片区V3",
     "user_input":"陪老人不能赶，3 站之内走完。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.6,budget_per_person=120,target_start="14:30",duration_hours=3.0),
     "audience":"friend","contact":"我爸"},
    {"id":"S88","title":"陪父母京菜·簋街","persona":"with_parents","area":"东直门-簋街片区",
     "user_input":"陪父母吃北京菜，老人怕辣，避开麻小。",
     "prefs":dict(persona="with_parents",party_size=3,diet_flags=["no_spicy"],walk_radius_km=1.0,budget_per_person=180,target_start="17:30",duration_hours=3.5),
     "audience":"friend","contact":"我妈"},
    {"id":"S89","title":"陪父母看戏·正乙祠","persona":"with_parents","area":"前门-鲜鱼口片区",
     "user_input":"陪父母去前门附近吃饭看戏曲。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=200,target_start="17:00",duration_hours=4.5),
     "audience":"friend","contact":"我爸"},
    {"id":"S90","title":"陪父母逛展·美术馆","persona":"with_parents","area":"中国美术馆-五四大街片区",
     "user_input":"带父母看美术馆 + 吃顿正经饭。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=180,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S91","title":"陪父母极低预算·和平里","persona":"with_parents","area":"和平里片区V3",
     "user_input":"父母节俭，找便宜实惠的家常菜。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.8,budget_per_person=70,target_start="11:30",duration_hours=3.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S92","title":"陪父母烤鸭·前门","persona":"with_parents","area":"前门片区",
     "user_input":"我爸第一次来北京想吃正宗烤鸭，要老字号。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=300,target_start="17:30",duration_hours=3.5),
     "audience":"friend","contact":"我爸"},
    {"id":"S93","title":"陪父母上香·法源寺","persona":"with_parents","area":"陶然亭片区",
     "user_input":"妈妈想去法源寺上香，再吃顿斋饭。",
     "prefs":dict(persona="with_parents",party_size=3,diet_flags=["vegetarian"],walk_radius_km=1.0,budget_per_person=120,target_start="09:30",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S94","title":"陪父母牛街·牛街V3","persona":"with_parents","area":"牛街片区V3",
     "user_input":"陪我爷爷奶奶去牛街吃清真。",
     "prefs":dict(persona="with_parents",party_size=4,diet_flags=["halal"],walk_radius_km=0.8,budget_per_person=130,target_start="11:30",duration_hours=3.5),
     "audience":"friend","contact":"我妈"},
    {"id":"S95","title":"陪父母安静·后海","persona":"with_parents","area":"什刹海-后海片区",
     "user_input":"陪父母在后海找安静地方坐坐，避开酒吧街。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=140,target_start="14:30",duration_hours=3.5),
     "audience":"friend","contact":"我妈"},
    {"id":"S96","title":"陪父母雨天·王府井","persona":"with_parents","area":"王府井片区V3",
     "user_input":"今天下雨，带父母王府井室内吃饭逛商场。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.6,budget_per_person=180,target_start="14:00",duration_hours=3.5),
     "audience":"friend","contact":"我爸"},
    {"id":"S97","title":"陪父母古迹·天坛","persona":"with_parents","area":"天坛片区",
     "user_input":"周末带父母去天坛公园，吃京味家常。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.5,budget_per_person=160,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
    {"id":"S98","title":"陪父母短行·建国门","persona":"with_parents","area":"建国门片区V3",
     "user_input":"父母腿脚不便，2 小时内吃个饭逛一站。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=0.5,budget_per_person=160,target_start="11:30",duration_hours=2.0),
     "audience":"friend","contact":"我爸"},
    {"id":"S99","title":"陪父母博物馆+饭·国博","persona":"with_parents","area":"天安门-故宫片区",
     "user_input":"带父母看国博，结束附近吃顿好的。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.5,budget_per_person=220,target_start="13:00",duration_hours=4.5),
     "audience":"friend","contact":"我爸"},
    {"id":"S100","title":"陪父母京味老字号·西四","persona":"with_parents","area":"西单-金融街片区",
     "user_input":"带父母吃北京老字号，再走走二环。",
     "prefs":dict(persona="with_parents",party_size=3,walk_radius_km=1.0,budget_per_person=180,target_start="14:00",duration_hours=4.0),
     "audience":"friend","contact":"我妈"},
]


def step_to_dict(s):
    return {"step_index": s.step_index, "kind": s.kind, "start_time": s.start_time,
            "duration_min": s.duration_min, "poi_id": s.poi_id, "poi_name": s.poi_name,
            "mode_to_here": s.mode_to_here, "rationale": s.rationale,
            "is_rerouted": s.is_rerouted}


def event_to_dict(ev):
    return {"failed_step_idx": ev.failed_step_idx, "failed_poi_name": ev.failed_poi_name,
            "reason": ev.reason, "evidence": list(ev.evidence),
            "replacement_poi_name": ev.replacement_poi_name}


def run_one(sc):
    sid = f"demo-{sc['id']}-{int(time.time())}"
    set_session(sid); clear_session(sid)
    prefs = UserPreferences(**sc["prefs"])
    out = {"scenario": sc["id"], "title": sc["title"], "session_id": sid,
           "input": {"user_input": sc["user_input"], "persona": sc["persona"],
                     "area_anchor": sc["area"], "prefs": sc["prefs"]}}
    t0 = time.time()
    try:
        p1 = make_plan(user_input=sc["user_input"], persona=sc["persona"],
                       prefs=prefs, area_anchor=sc["area"])
        t_plan = time.time() - t0
        t1 = time.time()
        p2, events = probe_plan(p1, prefs=prefs)
        t_probe = time.time() - t1
        card = render_im_card(p2, audience=sc["audience"])
        calls = fetch_calls(session_id=sid, limit=200)
        out.update({
            "ok": True,
            "v1": {"persona": p1.persona, "area_anchor": p1.area_anchor,
                   "summary": p1.summary, "steps": [step_to_dict(s) for s in p1.steps]},
            "events": [event_to_dict(e) for e in events],
            "v2": {"persona": p2.persona, "area_anchor": p2.area_anchor,
                   "summary": p2.summary, "steps": [step_to_dict(s) for s in p2.steps]},
            "im_card": {"title": card.title, "body": card.body,
                        "actions": [a["label"] for a in card.actions],
                        "audience": sc["audience"], "contact": sc["contact"]},
            "tool_calls": [
                {"timestamp": c["timestamp"], "tool_name": c["tool_name"],
                 "latency_ms": c["latency_ms"], "status": c["status"],
                 "params_brief": (c["params_json"] or "")[:120]}
                for c in calls],
            "timing": {"plan_s": round(t_plan,1), "probe_s": round(t_probe,1),
                       "total_s": round(time.time()-t0,1)},
        })
        print(f"[{sc['id']}] ok: v1 {len(p1.steps)} 步, v2 {len(p2.steps)} 步, "
              f"{len(events)} reroute, {out['timing']['total_s']}s", flush=True)
    except Exception as e:
        out.update({"ok": False, "error": f"{type(e).__name__}: {e}",
                    "traceback": traceback.format_exc()})
        print(f"[{sc['id']}] ERROR: {type(e).__name__}: {str(e)[:120]}", flush=True)
    return out


def main():
    out_path = ROOT / "data" / "longcat_demo_results.json"
    results = []
    t0 = time.time()
    for i, sc in enumerate(SCENARIOS, 1):
        print(f"\n=== [{i}/{len(SCENARIOS)}] {sc['id']} ===", flush=True)
        results.append(run_one(sc))
        # 每 5 个增量保存，防中断
        if i % 5 == 0:
            out_path.write_text(json.dumps(results, ensure_ascii=False, indent=2))
    out_path.write_text(json.dumps(results, ensure_ascii=False, indent=2))
    n_ok = sum(1 for r in results if r.get("ok"))
    print(f"\n完成 {n_ok}/{len(results)}，总耗时 {time.time()-t0:.0f}s")
    print(f"写入 {out_path}")


if __name__ == "__main__":
    main()
